// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngrmthktbtrigiktnohi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncm10aGt0YnRyaWdpa3Rub2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjQ1NDUsImV4cCI6MjA1OTgwMDU0NX0.qYRNRlXDj-Kv0bLATJrkcXmqWMR-WtxWfmsVxZwIzM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);